### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by iZh7** [purseclab/DnD#4]
Traceback (most recent call last):
  File "decompiler.py", line 175, in <module>
    decompile(sys.argv[1], sys.argv[2])
  File "decompiler.py", line 138, in decompile
    lifted_ast = lift_func_to_ast(proj, f)
  File "decompiler.py", line 62, in lift_func_to_ast
    lifted_ast = lift(proj, mem_write_dict, solver)
  File "/home/Newdisk2/jianghaiqi/DnD/src/lifter.py", line 759, in lift
    lifted_ast = lift_mem_write(proj, new_mem_write_dict, solver)
  File "/home/Newdisk2/jianghaiqi/DnD/src/lifter.py", line 557, in lift_mem_write
    outer_loop = list(mem_write_dict.values())[0].outer_loop

IndexError: list index out of range

**Comment by BruceZhao0728** [comment]
Hi, I met the same problem. How did you solve it?

> Traceback (most recent call last): File "decompiler.py", line 175, in decompile(sys.argv[1], sys.argv[2]) File "decompiler.py", line 138, in decompile lifted_ast = lift_func_to_ast(proj, f) File "decompiler.py", line 62, in lift_func_to_ast lifted_ast = lift(proj, mem_write_dict, solver) File "/home/Newdisk2/jianghaiqi/DnD/src/lifter.py", line 759, in lift lifted_ast = lift_mem_write(proj, new_mem_write_dict, solver) File "/home/Newdisk2/jianghaiqi/DnD/src/lifter.py", line 557, in lift_mem_write outer_loop = list(mem_write_dict.values())[0].outer_loop
> 
> IndexError: list index out of range
